version: 0.2  
phases:  
  install:
    commands:
      - aws cloudformation package --template-file index-photos.yaml --s3-bucket backend-deployement-pipeline-bucket --output-template-file index-photos.yaml
artifacts:  
  type: zip
  files:
    - index-photos.yaml